### ISSUE TITLE
Flag id for Moksha language is presently missing

### ISSUE THREAD

**Issue by rueter** [giellalt/keyboard-mdf#1]
**Flag for quick identification of Moksha-language keyboard**

When working with several languages alternately, it saves a lot of time if I can identify the input language by simple coloring instead of a bare keyboard icon.

In earlier Mac versions, there has been a flag present, such as [https://en.m.wikipedia.org/wiki/File:Flag_of_the_Moksha_people.svg](https://en.m.wikipedia.org/wiki/File:Flag_of_the_Moksha_people.svg)

**Comment by snomos** [comment]
See comment in https://github.com/giellalt/keyboard-myv/issues/1 🙂
